### PR TITLE
Notes support [for COM-572]

### PR DESCRIPTION
**Pull request by pbx**
For onDemand ticket COM-572.

### CODE REVIEW

**Comment by benspaulding** [comment]
I don’t think we actually want to merge this into master do we? Hopefully running our own fork of this is temporary. We should keep this in a notes-support branch for now, and help get notes support merged into the main project.

Anyone see issues with that?

**Comment by iamriel** [comment]
I agree.  I also believe that the authors of python-pptx are working on the notes support themselves.

**Comment by benspaulding** [comment]
@iamriel Can you make ticket in JIRA for us to review the main project’s notes support ticket and do what we can to help land it?

**Comment by iamriel** [comment]
@benspaulding I have created the ticket in jira, COM-1068

**Comment by benspaulding** [comment]
Great, thanks.

I propose that we decline this pull request for now. Hopefully we can help merge the main one, or create our own PR into the main one, rather than master in this one.

**Comment by pbx** [comment]
Yeah. I opened this PR just to give us a way to review the new code. Working to get these (or equivalent) changes into the upstream repo is the way to go, I agree.

**Pull request closed without merging**
